In [35]:
import pandas as pd
import geopy
import json

In [36]:
data_cafes = pd.read_csv('maps_google_scraped_final_dataset_V6.csv')
data_cafes.columns

Index(['placeId', 'searchString', 'title', 'categoryName', 'address', 'street',
       'city', 'postalCode', 'claimThisBusiness', 'location', 'totalScore',
       'temporarilyClosed', 'categories', 'cid', 'reviewsCount',
       'reviewsDistribution', 'openingHours', 'url', 'coords', 'neigbourhood'],
      dtype='object')

In [37]:
loc_data_cafes = data_cafes[['placeId', 'title', 'location']]
loc_data_cafes

# null = loc_data_cafes[loc_data_cafes['location'].isna() == True]

,placeId,title,location
0,ChIJe8xi1c-WEkcRZHdDHuo3j90,Kavárna U Šimpanze,"{'lat': 49.2305035, 'lng': 16.5337673}"
1,ChIJowGU1lKXEkcRhurHt6Lp8WA,coffee,"{'lat': 49.2333335, 'lng': 16.5308843}"
2,ChIJhYGFpheXEkcRajb-rh-zrNw,Křupkafé,"{'lat': 49.2339446, 'lng': 16.5343742}"
3,ChIJObMrvW-REkcRVzYBCe8TIb0,Kavárna Dallmayr,"{'lat': 49.2609078, 'lng': 16.5798162}"
4,ChIJwamoDsSREkcR9p9fj5gJeFs,Kafe a slanina,"{'lat': 49.2452964, 'lng': 16.5818784}"
...,...,...,...
420,ChIJe_ylhAKVEkcR7s1u0ojXXlU,Ema Cafe,"{'lat': 49.1925629, 'lng': 16.6048872}"
421,ChIJS6BBUcaVEkcR4ZT1jabPeMo,tyjátr coffee & wine,"{'lat': 49.1943746, 'lng': 16.6047935}"
422,ChIJLxTYoHuUEkcRy8XHNLCvtIY,Kinokavárna Brno,"{'lat': 49.217818, 'lng': 16.6207745}"
423,ChIJj5cikNKVEkcRiukU7AjL2ow,Patio Café & Bar,"{'lat': 49.1932345, 'lng': 16.6052392}"
424,ChIJS0FEsvmVEkcR9zM01uPpfjc,OC Nosreti - Café 52,"{'lat': 49.1909134, 'lng': 16.6222443}"

In [38]:
print(loc_data_cafes['location'].apply(type).unique())

[<class 'str'>]

In [39]:
loc_data_cafes['location'] = loc_data_cafes['location'].apply(lambda x: json.loads(x.replace("'", '"')))

C:\Users\elstr\AppData\Local\Temp\ipykernel_24256\2468698276.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loc_data_cafes['location'] = loc_data_cafes['location'].apply(lambda x: json.loads(x.replace("'", '"')))

In [40]:
locations = pd.json_normalize(loc_data_cafes['location'])
locations

           lat        lng
0    49.230503  16.533767
1    49.233334  16.530884
2    49.233945  16.534374
3    49.260908  16.579816
4    49.245296  16.581878
..         ...        ...
420  49.192563  16.604887
421  49.194375  16.604793
422  49.217818  16.620774
423  49.193235  16.605239
424  49.190913  16.622244

[425 rows x 2 columns]

In [43]:
loc_data_cafes_normalized = pd.concat([loc_data_cafes.drop('location', axis=1), locations], axis=1)
loc_data_cafes_normalized = loc_data_cafes_normalized.set_index('placeId')
loc_data_cafes_normalized

                                            title        lat        lng
placeId
ChIJe8xi1c-WEkcRZHdDHuo3j90    Kavárna U Šimpanze  49.230503  16.533767
ChIJowGU1lKXEkcRhurHt6Lp8WA                coffee  49.233334  16.530884
ChIJhYGFpheXEkcRajb-rh-zrNw              Křupkafé  49.233945  16.534374
ChIJObMrvW-REkcRVzYBCe8TIb0      Kavárna Dallmayr  49.260908  16.579816
ChIJwamoDsSREkcR9p9fj5gJeFs        Kafe a slanina  49.245296  16.581878
...                                           ...        ...        ...
ChIJe_ylhAKVEkcR7s1u0ojXXlU              Ema Cafe  49.192563  16.604887
ChIJS6BBUcaVEkcR4ZT1jabPeMo  tyjátr coffee & wine  49.194375  16.604793
ChIJLxTYoHuUEkcRy8XHNLCvtIY      Kinokavárna Brno  49.217818  16.620774
ChIJj5cikNKVEkcRiukU7AjL2ow      Patio Café & Bar  49.193235  16.605239
ChIJS0FEsvmVEkcR9zM01uPpfjc  OC Nosreti - Café 52  49.190913  16.622244

[425 rows x 3 columns]

In [44]:
loc_data_cafes_normalized.to_csv('location_cafes.csv')